### ISSUE TITLE
Mitre Attack Navigator missing Technique control 

### ISSUE THREAD

**Issue by OtherPeoplesEnemy** [CyberCX-STA/PurpleOps#19]
original ![image](https://github.com/CyberCX-STA/PurpleOps/assets/16155154/947b4e8d-450a-4cad-bd1b-6de1f1ea165f)

Purple ops 
![image](https://github.com/CyberCX-STA/PurpleOps/assets/16155154/1f64ba14-03a2-4afb-8a5c-1557e1c9c75d)

Attack Navigator is missing the Technique control in the menu.  This makes it impossible to properly export the data in json.

Update

From looking at it looks like you are just running mitre navigator in an Iframe.  Iframe is probably just not rendering properly.   I would also give people an option to configure there own navigator instead of using the public version.

**Comment by Harrison-Mitchell** [comment]
Nice catch - seems one of the query params used to tailor the view breaks the recently updated v5.0+ of navigator:

```
leave_site_dialog=false&tabs=false&header=false&layer_info=false&color_setup=false&toggle_hide_disabled=false&legend=false&disable_techniques=false&manual_color=false&background_color=false&scoring=false&comments=false&comment_underline=false&links=false&link_underline=false&metadata=false&clear_annotations=false
```

By dropping it to just:

```
&leave_site_dialog=false&tabs=false&header=false&layer_info=false
```

It fixed the issue.

We're looking at baking navigator into PurpleOps directly rather than leveraging an iFrame, but we've got juicier stuff on the roadmap so this will remain for a bit - a reminder you can export the navigator JSON and import it into whatever navigator you have setup too!
